// src/app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TreeServiceConnect - Find Tree Services in East Texas & North Louisiana',
  description: 'Connect with qualified tree service professionals in East Texas and North Louisiana. Get free quotes for tree removal, trimming, stump grinding, and emergency services.',
  keywords: 'tree service, tree removal, stump grinding, tree trimming, East Texas, North Louisiana, Kilgore, Longview, Henderson, Tyler, Shreveport',
  authors: [{ name: 'TreeServiceConnect' }],
  openGraph: {
    title: 'TreeServiceConnect - Find Tree Services in East Texas',
    description: 'Get free quotes from qualified tree service professionals in your area.',
    type: 'website',
  },
  icons: {
    icon: [
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' }
    ],
    apple: { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-JYYKB7XHJ6"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-JYYKB7XHJ6');
            `,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "name": "TreeServiceConnect",
              "description": "Directory of qualified tree service professionals in East Texas and North Louisiana",
              "url": "https://treeserviceconnect.com",
              "potentialAction": {
                "@type": "SearchAction",
                "target": "https://treeserviceconnect.com/cities?q={search_term_string}",
                "query-input": "required name=search_term_string"
              },
              "mainEntity": {
                "@type": "ItemList",
                "name": "Tree Service Directory",
                "description": "Directory of tree service companies in East Texas and North Louisiana",
                "itemListElement": [
                  {
                    "@type": "Service",
                    "name": "Tree Removal Services",
                    "areaServed": ["Kilgore, TX", "Longview, TX", "Henderson, TX", "Tyler, TX", "Shreveport, LA"]
                  },
                  {
                    "@type": "Service", 
                    "name": "Tree Trimming Services",
                    "areaServed": ["Kilgore, TX", "Longview, TX", "Henderson, TX", "Tyler, TX", "Shreveport, LA"]
                  },
                  {
                    "@type": "Service",
                    "name": "Stump Grinding Services", 
                    "areaServed": ["Kilgore, TX", "Longview, TX", "Henderson, TX", "Tyler, TX", "Shreveport, LA"]
                  },
                  {
                    "@type": "Service",
                    "name": "Emergency Tree Services",
                    "areaServed": ["Kilgore, TX", "Longview, TX", "Henderson, TX", "Tyler, TX", "Shreveport, LA"]
                  }
                ]
              }
            })
          }}
        />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
